name       : sharutils
version    : 4.15.2
release    : 6
source     :
    - https://ftp.gnu.org/gnu/sharutils/sharutils-4.15.2.tar.xz : 2b05cff7de5d7b646dc1669bc36c35fdac02ac6ae4b6c19cb3340d87ec553a9a
homepage   : http://www.gnu.org/software/sharutils/
license    :
    - GPL-3.0
summary    : Creates "shell archives" (or shar files) which are in text format and
    can be mailed.
component  : system.base
description: |
    'shar' makes so-called shell archives out of many files, preparing
    them for transmission by electronic mail services.  `unshar' helps
    unpacking shell archives after reception.  Other related utility
    programs help with other tasks.
    .
    'uuencode' prepares a file for transmission over an electronic
    channel which ignores or otherwise mangles the eight bit (high
    order bit) of bytes.  'uudecode' does the converse transformation.
    Homepage:

setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-1000097.patch
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
